# Generated by Django 5.2.6 on 2025-09-30 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("object_key", models.CharField(max_length=500, unique=True)),
                ("bucket_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upload_progress", models.FloatField(default=0.0)),
                ("upload_id", models.CharField(blank=True, max_length=100)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("unlisted", "Unlisted"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maiu_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "maiu_video_uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.PositiveIntegerField()),
                ("etag", models.CharField(blank=True, max_length=100)),
                ("size", models.BigIntegerField()),
                ("is_uploaded", models.BooleanField(default=False)),
                (
                    "video_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="maiu.videoupload",
                    ),
                ),
            ],
            options={
                "db_table": "maiu_upload_chunks",
                "ordering": ["part_number"],
            },
        ),
        migrations.AddIndex(
            model_name="videoupload",
            index=models.Index(
                fields=["uploader", "-created_at"],
                name="maiu_video__uploade_c30bd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoupload",
            index=models.Index(fields=["status"], name="maiu_video__status_5602ff_idx"),
        ),
        migrations.AddIndex(
            model_name="videoupload",
            index=models.Index(
                fields=["visibility", "-created_at"],
                name="maiu_video__visibil_424c5a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uploadchunk",
            unique_together={("video_upload", "part_number")},
        ),
    ]
